CREATE OR REPLACE PROCEDURE FIND_PLANE(FLIGHT IN NUMBER,TIME IN NUMBER)
IS 
   location VARCHAR2(50);
BEGIN
   SELECT PLACE INTO location 
	 FROM Location
	 WHERE (FLIGHT = Flight_No) AND( TIME >= Start_Time) AND ( TIME <= End_Time);
	
EXCEPTION
   WHEN NO_DATA_FOUND THEN 
		 RETURN -1;
	 WHEN OTHERS THEN
		 RAISE; 
END;
/