CREATE TABLE Passenger(
   ID NUMBER(5) NOT NULL,
	 First_Name VARCHAR2(50) NOT NULL,
	 Last_Name VARCHAR2(50) NOT NULL,
	 Age NUMBER(5) NOT NULL,
	 Email VARCHAR2(50) NOT NULL,
	 Address VARCHAR2(50) NOT NULL,
	 PRIMARY KEY(ID)
);

CREATE TABLE LoginPsngr(
	ID NUMBER(5) PRIMARY KEY,
	Password VARCHAR2(50) NOT NULL,
	FOREIGN KEY(ID) REFERENCES Passenger(ID)
);

CREATE TABLE Employees(
  ID NUMBER(5) NOT NULL,
	First_Name VARCHAR2(50) NOT NULL,
	Last_Name VARCHAR2(50) NOT NULL,
	Salary NUMBER(10) NOT NULL,
	Phone_Number NUMBER(15) NOT NULL,
	Address VARCHAR2(50) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE LoginAsAdmin(
  ID NUMBER(5) PRIMARY KEY,
	Password VARCHAR2(50) NOT NULL,
	SecurityCode VARCHAR2(50) NOT NULL,
	FOREIGN KEY(ID) REFERENCES Employees(ID)
);


CREATE TABLE Airline(
  Flight_No NUMBER(5) NOT NULL,
	Name VARCHAR2(50) NOT NULL,
	ID NUMBER(5) NOT NULL,
	City VARCHAR2(50) NOT NULL,
	Capacity NUMBER(5) NOT NULL,
	Country VARCHAR2(50) NOT NULL,
	PRIMARY KEY(Flight_No)
);


CREATE TABLE Ticket(
   Flight_No NUMBER(5) PRIMARY KEY,
	 Source VARCHAR2(50) NOT  NULL,
	 Destination VARCHAR2(50) NOT NULL,
	 Flight_Time DATE NOT NULL,
	 Class VARCHAR2(50) NOT NULL,
	 FOREIGN KEY(Flight_No) REFERENCES Airline(Flight_No)
);

CREATE TABLE AirPlane(
   Name VARCHAR2(50) NOT NULL,
	 Source VARCHAR2(50) NOT NULL,
	 Destination VARCHAR2(50) NOT NULL,
	 PRIMARY KEY(Name)
);

CREATE TABLE Location(
    TimeRange NUMBER(5) PRIMARY KEY,
		Place VARCHAR2(50) NOT NULL,
		FOREIGN KEY(Place) REFERENCES AirPlane(Name)
);
		
  
    





